travis:
  secure:
    BINSTAR_TOKEN: iHcf5V51TKXM5be+GDSjpRlSEPhCkypy1HlWdtHUG3JC92zGc5sHN06ARDJIT8PRjpDapkoDbLsdHMkCCuD3p9YSGwjCIhF6QXPNYQzEnnYouu35s1Q0DygRNTctmoY31XosjrpK7jD0c1c6OEQTCWE4hD7/bmX4keg3HGBc8cr4E7DUkc/mYzIMqBqkgHAlA+Ap4tVQeaANG1QPUMkg61QxhIMBiNLvg2Wyqgy0Px1+Qy0UqMuFk61MBv9dKGXeoadmG5bRsnbswnxpEvbmnopfv0rtAoIz8xoyT0krwAc1Ge0v6h8RQz/LX4sCEtcdMWXqNH9NhV4bRWtLkDovUqwNK78dO6MeAQBwvn1YQl5AUQuIrCBuq/TMpkY0++9v2+e7191li2GM7SSpvbOi1Vy2kw3XxvQCTbe1Gwx4Ms0ZbYe9K4lBL9Fe24i/sRXeKaIs1eiYyQW2t/wRFlU7B2EHuZutY3tb8PXh2rqHzDBjLq94D3nA6wNpRcGO6Br7q/p8htnVA3l++SJc95zug7D8FiGPAVEep8t2xxBj96c989pP2eAy9zqDxZA3Rd3TbzLN21+BnKnbfAbG4hVJ38EPfVXEK4PH2QuXxh4e4rcr9aOQPiElrv5sEum+n1aEyWW6kRFmWaSR0d5bIU1UsuCSrzYF0oDgApTkMaarwpc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
